version: "3" 

networks: 
  default: 
    name: feedex_net 

services: 
  web: 
    build: . 
    # command: /app/bin/migrate_run
    # command: /bin/bash 
    ports: 
      - 5000:4000 
    volumes:
      - /tmp/feedex/src:/app
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: feedex_prod
      PGHOST: phx_db
      PGPORT: 5433
    depends_on:
      - phxdb

  phxdb:
    image: postgres
    container_name: phx_db
    ports: 
      - 5433:5432 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - /tmp/feedex/pgdata:/var/lib/postgresql/data
