use Mix.Config

config :ragged_data, RaggedData.Repo,
  username: "postgres",
  password: "postgres",
  database: "ragged_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :ragged_data, RaggedData.Influx,
  database: "inf_ragged_dev"

# ---------------------------------------------------

config :ragged_web, RaggedWeb.Endpoint,
  http: [port: 4060],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../apps/ragged_web/assets", __DIR__)
    ]
  ]

# ---------------------------------------------------

config :ragged_web, RaggedWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ragged_web/{live,views}/.*(ex)$",
      ~r"lib/ragged_web/templates/.*(eex)$"
    ]
  ]

config :mix_test_watch, clear: true

# ---------------------------------------------------

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.
