name: CD_FEEDEX
on:
  push:
    branches: 
      - master
  workflow_dispatch:
jobs:
  ci:
    uses: ./.github/workflows/base_ci.yml
  cd: 
    runs-on: self-hosted
    needs: ci 
    name: Build and Deploy 
    env: 
      MIX_ENV: prod
      ImageOS: ubuntu22
    steps: 
      - name: test script relative path 
        run: ~/.gh_actions/test.sh
      - name: feedex script relative path 
        run: ~/.gh_actions/feedex_build_deploy "${{ secrets.FEEDEX_TOKEN }}"

