name: CI_FEEDEX
on:
  push:
    branches-ignore: 
      - master
  workflow_dispatch:
jobs:
  ci:
    uses: ./.github/workflows/base_ci.yml
  alt: 
    name: Prototype Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "HELLO WORLD"
